// 모두의 문제 연구소 - 학과 및 교수님 데이터

export const departmentInfo = {
    title: "수리데이터사이언스학과",
    description: "수리데이터사이언스학과는 현대 사회의 각종 방대하고 복잡한 문제들을 데이터에 기반하여 수학적으로 모델링하고, 알고리즘을 통해 해결 방법을 탐구하는 융합 학문을 배웁니다. 모두의 문제 연구소는 본 학과의 지도 아래 설립되었습니다.",
    url: "https://mds.hanyang.ac.kr/",
    professors: [
        {
            id: 1,
            name: "정혜영",
            title: "부교수 / 전임교원",
            department: "수리데이터사이언스학과",
            position: "수리데이터사이언스학과장",
            research: "데이터사이언스, 신뢰가능 인공지능",
            phone: "031-400-5463",
            email: "hyjunglove@hanyang.ac.kr",
            image: "https://m.hanyang.ac.kr/huas/staff/image.page?imageNo=vWQ3bOI3TxCPpflLIfT4sw%3D%3D",
            appointment: "2020년",
            education: [
                { year: "1998", text: "경상대학교 이학사" },
                { year: "2001", text: "연세대학교 이학석사(일반대학원)" },
                { year: "2014", text: "연세대학교 이학박사" }
            ],
            career: [
                { period: "2016.03.01 ~ 2020.02.29", text: "서울대학교 강의부교수" },
                { period: "2014.09.01 ~ 2016.02.29", text: "서울대학교 시간강사" },
                { period: "2014.07.01 ~ 2016.02.29", text: "서울대학교 박사후연구원" },
                { period: "2007.09.01 ~ 2014.08.31", text: "연세대학교 시간강사" },
                { period: "2000.12.01 ~ 2002.07.26", text: "오비씨소프트(오픈비지니스컨설팅) 컨설턴트" }
            ],
            papers: [
                { date: "2026.01.21", title: "Do Geopolitical Shocks Move the Primary Market? Evidence from U.S. Treasury Auction Yields", journal: "APPLIED ECONOMICS LETTERS", classification: "SSCI" },
                { date: "2025.10.31", title: "AdaBoost 기반 신용카드 이상거래 데이터 증강 및 적대적 학습 분석", journal: "응용통계연구", classification: "등재학술지" },
                { date: "2025.08.25", title: "AI 기반 운영리스크 관리 현황 및 선제적 KRI 관리", journal: "문화기술의 융합", classification: "등재학술지" },
                { date: "2025.08.22", title: "설명가능한 인공지능(XAI)의 금융리스크 관리 적용 동향과 과제", journal: "문화기술의 융합", classification: "등재학술지" },
                { date: "2024.09.15", title: "Fuzzy α-Cut Lasso for Handling Diverse Data Types in LR-Fuzzy Outcomes", journal: "INTERNATIONAL JOURNAL OF FUZZY SYSTEMS", classification: "SCI-E" },
                { date: "2024.07.31", title: "신용평가에서 설명가능 인공지능의 활용에 관한 연구", journal: "문화기술의 융합", classification: "등재학술지" },
                { date: "2024.02.01", title: "딥러닝 기반 시계열 분석 모델의 불확실성 정량화 비교 연구", journal: "Journal of The Korean Data Analysis Society", classification: "등재학술지" },
                { date: "2024.02.01", title: "금융에서의 시계열 이미지화 인코딩에 따른 불확실성 정량화", journal: "한국지능시스템학회 논문지", classification: "등재학술지" },
                { date: "2023.12.01", title: "다중 분류에서의 불확실성 정량화에 대한 연구", journal: "한국지능시스템학회 논문지", classification: "등재학술지" },
                { date: "2023.10.01", title: "자율 운항을 위한 U-Net 기반의 deblurring 안정성 연구", journal: "한국지능시스템학회 논문지", classification: "등재학술지" },
                { date: "2023.05.31", title: "A Study of Least Absolute Deviation Fuzzy Transform", journal: "INTERNATIONAL JOURNAL OF FUZZY SYSTEMS", classification: "SCI-E" },
                { date: "2023.03.01", title: "Deep SHAP을 통한 Shapley value의 노이즈 강건성 분석", journal: "한국지능시스템학회 논문지", classification: "등재학술지" },
                { date: "2022.12.01", title: "이변수 함수에 대한 최소 절대 편차 퍼지 변환", journal: "한국지능시스템학회 논문지", classification: "등재학술지" },
                { date: "2022.05.30", title: "Fuzzy Transform and Least-Squares Fuzzy Transform: Comparison and Application", journal: "INTERNATIONAL JOURNAL OF FUZZY SYSTEMS", classification: "SCI-E" },
                { date: "2022.04.30", title: "최소 절대 편차 근사를 이용한 퍼지 변환", journal: "한국지능시스템학회 논문지", classification: "등재학술지" },
                { date: "2021.08.01", title: "이상치에 따른 불확실성에 관한 연구", journal: "한국지능시스템학회 논문지", classification: "등재학술지" },
                { date: "2021.02.08", title: "Impacts of public medical insurance reforms on households: An application of fuzzy cognitive map for scenario evaluation", journal: "SOFT COMPUTING", classification: "SCI-E" },
                { date: "2020.10.31", title: "퍼지 자료를 가진 능형 회귀모형", journal: "한국지능시스템학회 논문지", classification: "등재학술지" },
                { date: "2020.09.25", title: "Hybrid Fuzzy Regression Analysis Using the F-Transform", journal: "APPLIED SCIENCES-BASEL", classification: "SCI-E" },
                { date: "2020.09.12", title: "Ridge Fuzzy Regression Modelling for Solving Multicollinearity", journal: "MATHEMATICS", classification: "SCI-E" },
                { date: "2020.06.02", title: "Effects of Uncertainty Shocks on Household Consumption and Working Hours: A Fuzzy Cognitive Map-Based Approach", journal: "MATHEMATICS", classification: "SCI-E" },
                { date: "2019.10.18", title: "Fuzzy regression model using fuzzy partition", journal: "Journal of Physics: Conference Series", classification: "SCOPUS" },
                { date: "2019.10.01", title: "Ridge Fuzzy Regression Model", journal: "INTERNATIONAL JOURNAL OF FUZZY SYSTEMS", classification: "SCI-E" },
                { date: "2019.08.20", title: "Statistical inference for time series with non-precise data", journal: "INTERNATIONAL JOURNAL OF APPROXIMATE REASONING", classification: "SCI" },
                { date: "2019.07.26", title: "국회 법안 검토 기간의 생존함수 추정: 제 17, 18, 19대 국회의 사례를 바탕으로", journal: "응용통계연구", classification: "등재학술지" },
                { date: "2019.07.11", title: "Multivariate Cluster-Based Multifactor Dimensionality Reduction to Identify Genetic Interactions for Multiple Quantitative Phenotypes", journal: "BIOMED RESEARCH INTERNATIONAL", classification: "SCI-E" },
                { date: "2019.01.12", title: "거래소 간 자산 교환비율 차이를 이용한 차익거래기회 분석", journal: "한국데이터정보과학회지", classification: "등재학술지" },
                { date: "2018.11.19", title: "의학 진단 및 생물 정보학 분야에서 퍼지 접근법의 적용에 관한 연구", journal: "한국데이터정보과학회지", classification: "등재학술지" },
                { date: "2018.07.01", title: "Fuzzy heaping mechanism for heaped count data with imprecision", journal: "SOFT COMPUTING", classification: "SCI-E" },
                { date: "2018.05.18", title: "Fuzzy regression model with monotonic response function", journal: "대한수학회논문집", classification: "등재학술지" },
                { date: "2018.04.20", title: "Fuzzy set-based generalized multifactor dimensionality reduction analysis of gene-gene interactions", journal: "BMC MEDICAL GENOMICS", classification: "SCI-E" },
                { date: "2017.12.01", title: "A novel forecasting method based on F-transform and fuzzy time series", journal: "INTERNATIONAL JOURNAL OF FUZZY SYSTEMS", classification: "SCI-E" },
                { date: "2017.03.23", title: "Analysis of variance for fuzzy data based on permutation method", journal: "International Journal of Fuzzy Logic and Intelligent systems", classification: "등재학술지" },
                { date: "2016.10.19", title: "A novel fuzzy set based multifactor dimensionality reduction method for detecting gene–gene interaction.", journal: "COMPUTATIONAL BIOLOGY AND CHEMISTRY", classification: "SCI" },
                { date: "2016.10.04", title: "Statistical analysis for aggregated count data in genetic association studies", journal: "INTERNATIONAL JOURNAL OF DATA MINING AND BIOINFORMATICS", classification: "SCI-E" },
                { date: "2016.01.31", title: "On Theil's method in fuzzy linear regression models", journal: "Communications of the Korean Mathematical Society", classification: "SCOPUS" },
                { date: "2015.09.01", title: "Fuzzy linear regression using rank transform method", journal: "FUZZY SETS AND SYSTEMS", classification: "SCI" },
                { date: "2015.04.01", title: "The statistical inferences of fuzzy regression based on bootstrap techniques", journal: "SOFT COMPUTING", classification: "SCI-E" },
                { date: "2015.01.31", title: "Forecast of Korea Defense Expenditures based on Time Series Models", journal: "Communications for Statistical Applications and Methods", classification: "등재학술지" },
                { date: "2014.02.01", title: "A unified approach to asymptotic behaviors for the autoregressive model with fuzzy data", journal: "INFORMATION SCIENCES", classification: "SCI" }
            ],
            books: [
                { date: "2024.01.10", title: "AI시대의 통계적 예측 : 시계열의 인공신경망 예측", publisher: "경문사" }
            ],
            conferences: [
                { date: "2025.12.19", title: "The Effect of Optimization Methods on OOD Detection Performance Based on Uncertainty Measures", society: "한국통계학회" },
                { date: "2025.12.19", title: "Lightweight Statistical Detection of Imperceptible Poisoning with Downscaling and Latent Shift Analysis", society: "한국통계학회" },
                { date: "2025.12.19", title: "Time Series Anomaly Detection Using Multi-Scale Smoothing Residual Heatmap", society: "한국통계학회" },
                { date: "2025.06.20", title: "A Study on Synthetic Data Generation and Performance Evaluation for Obesity Classification", society: "한국통계학회" },
                { date: "2025.06.20", title: "Quantifying Model Uncertainty via Loss Landscape Sharpness in Deep Learning", society: "한국통계학회" },
                { date: "2024.11.22", title: "A Study on the Reliability of Medical Diagnostics Using Deep Learning", society: "한국인공지능학회" },
                { date: "2024.08.17", title: "Understanding the Sources of Uncertainty in Deep Learning", society: "한국인공지능학회" },
                { date: "2024.07.05", title: "Active learning의성능향상을위한불확실성측도비교", society: "한국통계학회" },
                { date: "2023.12.01", title: "시계열 이미지화 인코딩을 통한 이상 탐지", society: "한국통계학회" },
                { date: "2023.12.01", title: "Active learning을 위한 불확실성 샘플링 기법에 관한 비교 연구", society: "한국통계학회" },
                { date: "2023.12.01", title: "베이지안 기법에 기반한 불확실성 측도 비교 연구", society: "한국통계학회" },
                { date: "2023.11.28", title: "인공지능, 신뢰할 수 있을까?", society: "국립경상대학교 수학과" },
                { date: "2023.11.24", title: "A Novel Algorithm to the Reliable Prediction using SHAP uncertainty", society: "한국인공지능학회" },
                { date: "2023.11.11", title: "금융에서의 시계열 이미지화 인코딩에 따른 불확실성 정량화", society: "한국지능시스템학회" },
                { date: "2023.11.11", title: "불확실성 정량화 방법의 비교 연구", society: "한국지능시스템학회" },
                { date: "2023.07.07", title: "딥러닝 기반 시계열 분석 모형의 불확실성 정량화 비교 연구", society: "한국자료분석학회" },
                { date: "2023.06.30", title: "Shapley Value에 기반한 예측 기여도의 불확실성에 관한 연구", society: "한국통계학회" },
                { date: "2023.06.30", title: "딥러닝 기반 모형과 ARIMA 모형을 활용한 시계열 예측 비교", society: "한국통계학회" },
                { date: "2023.06.30", title: "의료 이미지 분류에서의 불확실성 측정법 비교 분석", society: "한국통계학회" },
                { date: "2023.06.29", title: "Uncertainty quantification in deep learning for Medical Image Segmentation", society: "한국통계학회" },
                { date: "2023.04.15", title: "SHAP을 활용한 변수의 불확실성에 관한 연구", society: "한국지능시스템학회" },
                { date: "2023.04.15", title: "다중분류에서의 불확실성 정량화에 대한 연구", society: "한국지능시스템학회" },
                { date: "2023.04.15", title: "일별 주가 예측에 대한 불확실성 측도 비교", society: "한국지능시스템학회" },
                { date: "2022.12.02", title: "모형의 설명력을 고려한 SHAP 기반 변수선택 알고리즘", society: "한국통계학회" },
                { date: "2022.12.02", title: "신용평가에서 설명가능 인공지능의 활용에 관한 연구", society: "한국통계학회" },
                { date: "2022.12.02", title: "워드 임베딩 기법에 따른 모델 안정성에 관한 연구", society: "한국통계학회" },
                { date: "2022.11.30", title: "A Comparison Study of Fuzzy Transform based Approximation Methods", society: "Soft Computing and Intelligent Systems" },
                { date: "2022.11.05", title: "Least Absolute Deviation Fuzzy Transform", society: "Taiwan Fuzzy Systems Association (TFSA)" },
                { date: "2022.10.28", title: "자율 운항을 위한 U-Net 기반의 Deblurring 안정성 연구", society: "한국지능시스템학회" },
                { date: "2022.10.28", title: "불확실성 정량화에 대한 고찰", society: "한국지능시스템학회" },
                { date: "2022.06.24", title: "변수의 기여도 측정을 위한 Shapley Value의 통계적 고찰", society: "한국통계학회" },
                { date: "2022.05.14", title: "이변수 함수에 대한 최소 절대 편차 퍼지 변환", society: "한국지능시스템학회" },
                { date: "2022.05.14", title: "Deep SHAP을 통한 shapley value의 노이즈 강건성 분석", society: "한국지능시스템학회" },
                { date: "2021.12.16", title: "Least Absolute Deviations Fuzzy transform", society: "Korean Institute of Intelligent Systems (KIIS)" },
                { date: "2021.10.06", title: "Fuzzy Transform & Least-Squares Fuzzy Transform Comparison and Application", society: "Taiwan Fuzzy Systems Association (TFSA) and NFU" }
            ]
        }
    ]
};
